development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:4e721f39338ec68ebd06b1b8bfcc8f47@scat.redistogo.com:10205/
  channel_prefix: dlack_production
